#!/usr/bin/env python3
"""
Scrape all wine products from wine.md catalog and generate wine-data.js.
Uses only stdlib (urllib, re, json). Run: python3 scrape_wine_md.py
"""
import urllib.request
import urllib.error
import re
import json
import time
import os
import ssl

BASE = "https://wine.md/"
CATALOG_URL = BASE + "catalog/"
PER_PAGE = 21
MAX_PAGES = 120  # 21*120 = 2520 > 1937

# Avoid SSL verify failure on some systems
_ctx = ssl.create_default_context()
_ctx.check_hostname = False
_ctx.verify_mode = ssl.CERT_NONE

def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (compatible; WineCatalog/1.0)"})
    with urllib.request.urlopen(req, timeout=25, context=_ctx) as r:
        return r.read().decode("utf-8", errors="replace")

def extract_products(html):
    products = []
    # Split by product blocks (each card is in a div.product or we match form with pagetitle)
    blocks = re.split(r'<div class="product">', html)
    for block in blocks[1:]:  # skip first (header)
        link_m = re.search(r'href="(catalog/[^"]+)"[^>]*class="product-image', block)
        title_m = re.search(r'class="product-title">([^<]+)</a>', block)
        img_m = re.search(r'src="(/assets/images/products/\d+/[^"]+)"', block)
        price_m = re.search(r'name="price"\s+value="(\d+)"', block)
        if not link_m:
            continue
        path = link_m.group(1).strip()
        if path.endswith("/") or "/brand/" in path or "collections" in path:
            continue
        slug = path.split("/")[-1] if "/" in path else path
        name = title_m.group(1).strip() if title_m else slug.replace("-", " ").title()
        image_path = img_m.group(1) if img_m else ""
        price = int(price_m.group(1)) if price_m else 0
        if not image_path or "woodbag-logo" in image_path:
            continue
        image_url = (BASE.rstrip("/") + image_path) if image_path.startswith("/") else BASE + image_path
        image_url_full = image_url.replace("/small/", "/") if "/small/" in image_url else image_url
        products.append({
            "path": path,
            "slug": slug,
            "name": name,
            "imageUrl": image_url_full,
            "imageUrlSmall": image_url,
            "price": price,
            "link": path if path.startswith("catalog/") else "catalog/" + path,
        })
    return products

def path_to_type(path):
    path_lower = path.lower()
    if "vinuri-spumante" in path_lower or "spumante" in path_lower:
        return "sparkling"
    if "vinuri-rosii" in path_lower or "vinuri-roșii" in path_lower:
        return "red"
    if "vinuri-roze" in path_lower or "vinuri-roze" in path_lower:
        return "rose"
    if "vinuri-dulci" in path_lower:
        return "white"  # sweet often white
    if "vinuri-albe" in path_lower:
        return "white"
    if "vinuri-de-colectie" in path_lower:
        return "red"  # default
    return "white"

def infer_brand(name):
    # Heuristic: known multi-word brands, then first two title-case words
    known = [
        "Castel Mimi", "Château Purcari", "Château Vartely", "Crama Mircesti", "Domeniile Vorniceni",
        "Et Cetera", "Vera Winery", "Vinaria Din Vale", "Gogu Winery", "Asconi", "Fautor",
        "Cricova", "Radacini", "Divus", "Purcari", "Equinox", "Mezalimpe", "Timbrus",
        "Tomai", "Aurelius", "Domeniile Cuza", "Vinum", "Barza Alba", "Corten",
        "Gitana", "Apriori", "Bardar", "Bostavan", "Academia", "Crama", "Vinaria",
    ]
    for brand in known:
        if name.startswith(brand):
            return brand
    words = name.split()
    if len(words) >= 2 and words[0][0].isupper() and words[1][0].isupper():
        return words[0] + " " + words[1]
    if words:
        return words[0]
    return "Moldova"

def main():
    seen = {}
    all_products = []
    for page in range(1, MAX_PAGES + 1):
        url = CATALOG_URL + ("?page=%d" % page) if page > 1 else CATALOG_URL
        print("Fetching page %d: %s" % (page, url), flush=True)
        try:
            html = fetch(url)
        except Exception as e:
            print("Error:", e, flush=True)
            break
        products = extract_products(html)
        if not products:
            print("No products on page %d, stopping." % page, flush=True)
            break
        for p in products:
            if p["slug"] in seen:
                continue
            seen[p["slug"]] = True
            p["type"] = path_to_type(p["path"])
            p["brand"] = infer_brand(p["name"])
            p["id"] = re.sub(r"[,/]", "-", p["slug"]).replace(" ", "-")
            p["productPageUrl"] = BASE + p["link"].lstrip("/")
            all_products.append(p)
        if len(products) == 0:
            break
        time.sleep(0.35)
    print("Total products: %d" % len(all_products), flush=True)

    # Build wine-data.js format
    lines = [
        "// Full catalog from wine.md – all brands and products with images from wine.md. Generated by scripts/scrape_wine_md.py",
        "window.WINE_PRODUCTS = [",
    ]
    for i, p in enumerate(all_products):
        # JS object: id, brand, name, type, imageUrl, price, rating, reviewCount, vintage, region, grape, abv, description, productPageUrl
        desc_esc = (p.get("description") or "").replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ")
        region = p.get("region") or "Moldova"
        grape = p.get("grape") or "Blend"
        abv = p.get("abv") or 12
        vintage = p.get("vintage") or ""
        rating = 4.0 + (i % 5) * 0.1
        review_count = 10 + (i % 50)
        img_full = p["imageUrl"].replace("'", "\\'")
        img_small = p.get("imageUrlSmall", p["imageUrl"]).replace("'", "\\'")
        obj = (
            "  { id: '%s', brand: '%s', name: '%s', type: '%s', imageUrl: '%s', imageUrlSmall: '%s', price: %d, rating: %.1f, reviewCount: %d, vintage: '%s', region: '%s', grape: '%s', abv: %s, description: '%s', productPageUrl: '%s' }"
            % (
                p["id"].replace("'", "\\'"),
                p["brand"].replace("'", "\\'"),
                p["name"].replace("'", "\\'"),
                p["type"],
                img_full,
                img_small,
                p["price"],
                rating,
                review_count,
                vintage,
                region.replace("'", "\\'"),
                grape.replace("'", "\\'"),
                str(abv) if isinstance(abv, (int, float)) else abv,
                desc_esc[:200] if desc_esc else ("Vin " + p["type"] + " – " + p["name"]).replace("'", "\\'")[:200],
                p["productPageUrl"].replace("'", "\\'"),
            )
        )
        lines.append(obj + ("," if i < len(all_products) - 1 else ""))
    lines.append("];")

    # Remove IIFE that overwrites imageUrl (we want to keep all wine.md images)
    lines.append("")
    lines.append("// wine.md image URLs are kept; no brokenHosts replacement for wine.md.")

    out_path = os.path.join(os.path.dirname(__file__), "..", "wine-data.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("Wrote %s with %d products." % (out_path, len(all_products)), flush=True)

if __name__ == "__main__":
    main()
